services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - phishing_network

  backend:
    build: ./phishing-app-backend
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/phishing_db
    ports:
      - "5000:5000"
    networks:
      - phishing_network

  frontend:
    build: ./phishing-app-frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - phishing_network

volumes:
  mongo_data:

networks:
  phishing_network:
    name: phishing_network
    driver: bridge